### ISSUE TITLE
Release under GPL

### ISSUE THREAD

**Issue by stbenjam** [jcmcken/foreman_custom_banner#3]
Every now and then people are looking for this feature in Foreman.  It's a great plugin, I'd like to package it up (addresses #2), but the license for this repo would need to be GPL because of how Foreman plugins work, see http://www.gnu.org/licenses/gpl-faq.en.html#GPLAndPlugins.

It's a small nitpick, but to get the package into the repos the licensing would need to be correct.

**Comment by tmiller** [comment]
http://www.apache.org/licenses/GPL-compatibility.html Apache 2.0 is compatible with GPL V3 which Foreman uses. In the link you provided it mentions that you can use GPL-compliant licenses . However, I did not take the time to make sure that the license is distributed in a GPL-compliant way.

**Comment by jcmcken** [comment]
Hi, sorry for the (extremely) delayed response. Does cbfcb7a work?

**Comment by stbenjam** [comment]
That would be fine, but I may have been wrong based on what @tmiller said. I'm not an expert on licensing, just know what I was told previously about other foreman plugins (but mostly they used our template which was GPL).

Anyway, if you want to leave it Apache licensed, I can open a packaging PR and see what gets said about it.

**Comment by jcmcken** [comment]
GPL vs non doesn't particularly matter to me in this case, I just wasn't sure whether just dropping the license into the repo was sufficient (the GPLv3 instructions indicate that you should drop licensing info into the header of each source file too, but the way people actually do it seems to differ). I pushed up the license from the template to be consistent with other plugins

**Comment by domcleal** [comment]
Thanks, I think this is correct.  Though Apache 2's compatible (i.e. the two works could be distributed together), in most cases plugins to Foreman would probably be considered derivative works of Foreman rather than a standalone piece of work, therefore should retain Foreman's GPLv3+ licence.

Putting the licence file in the base of the repo and included in the gem is usually enough, since the source files are unlikely to be distributed by themselves.  The gemspec is already correct, it will include the licence file in the gem.
